http://localhost:8080/categories/1

###

http://localhost:8080/categories

###
POST http://localhost:8080/Categories
Content-Type: application/json

{
    "name": "Okia"
}
###
PUT http://localhost:8080/Categories/10
Content-Type: application/json

{
    "name": "Ohaio"
}
###
DELETE http://localhost:8080/Categories/11
