GET http://localhost:8080/orders?storeId=1&orderStatus=Completed&day=1500

###
GET http://localhost:8080/products?q=Qu

###
POST http://localhost:8080/products
Content-Type: application/json

{
    "productName": "Xe dap",
    "brandId": 5,
    "categoryId": 7,
    "modelYear": 2016,
    "listPrice": 2999.99
}

###
PUT http://localhost:8080/products/322
Content-Type: application/json

{
    "productName": "Xe may o to",
    "brandId": 4,
    "categoryId": 7,
    "modelYear": 2016,
    "listPrice": 2999.99
}
###
DELETE http://localhost:8080/products/323